### ISSUE TITLE
Segmentation Fault when using CVODE_BDF with an ODEFunction with a JacVecOperator.

### ISSUE THREAD

**Issue by FHell** [SciML/Sundials.jl#221]
The following minimal example throws a segmentation fault, crashing the Julia runtime for me:

```julia
using OrdinaryDiffEq
using Sundials
using DiffEqOperators

omega = randn(10^3) .+ 1.
x0 = rand(10^3)

f = (dx,x,p,t) -> (dx .= p)

Jv = JacVecOperator(f, x0, omega, 0.0)

of = ODEFunction(f; jac_prototype=Jv)

prob = ODEProblem(of, x0, (0.,5.), omega)
solve(prob, CVODE_BDF())
```

**Comment by FHell** [comment]
I see. The issue is that if I get passed an ODEFunction I have no way of telling whether/which type of Jacobian it carries with it. Thus I can not tell which ODEFunctions I (or the users of my library) can safely solve with CVODE_BDF... Would it be sensible/possible to not pass incompatible Jacobians to CVODE_BDF inside solve/just ignore them inside Sundials.jl, possibly with warning?

**Comment by ChrisRackauckas** [comment]
Yeah, we can make it recognize it, throw a warning (under `verbose`), and ignore it so that it doesn't segfault.
