### ISSUE TITLE
Segmentation fault in tests on 32-bit architectures (i686 and arm)

### ISSUE THREAD

**Issue by ViralBShah** [SciML/Sundials.jl#223]
I just tried running the Sundials tests on Raspberry Pi and they failed with 1.3. Just reporting here for the record.

```
signal (11): Segmentation fault
in expression starting at /home/pi/.julia/packages/Sundials/MllUG/test/cvode_Roberts_dns.jl:66
_ZL22isExtendedBUILD_VECTORPN4llvm6SDNodeERNS_12SelectionDAGEb at /home/pi/julia-1.3.0/bin/../lib/julia/libLLVM-6.0.so (unknown line)
Allocations: 9997384 (Pool: 9996517; Big: 867); GC: 21
ERROR: Package Sundials errored during testing
```

``` 
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 4 (v7l)
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, cortex-a53)
```

**Comment by ChrisRackauckas** [comment]
For reference, the Sundials build is: https://github.com/JuliaDiffEq/SundialsBuilder/releases/tag/sundials-3.1.1.6 . I assume that segfault means we need to fix that binary builder repo build script.

**Comment by ViralBShah** [comment]
Is there a minimal example I can try? It could even be Julia itself crashing.

**Comment by ChrisRackauckas** [comment]
```julia
using Sundials
function lorenz(du,u,p,t)
 du[1] = 10.0(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end
u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz,u0,tspan)
sol = solve(prob,CVODE_Adams())
using Plots; plot(sol,vars=(1,2,3))
```

is what I'd try.

**Comment by ViralBShah** [comment]
No crash with that.

**Comment by ViralBShah** [comment]
Will that example call into BLAS/LAPACK?

**Comment by ViralBShah** [comment]
It's crashing here:

https://github.com/JuliaDiffEq/Sundials.jl/blob/90ec5466df22a61129c3d84665bb113cf6aafd81/test/cvode_Roberts_dns.jl#L66

**Comment by ViralBShah** [comment]
> For reference, the Sundials build is: https://github.com/JuliaDiffEq/SundialsBuilder/releases/tag/sundials-3.1.1.6 . I assume that segfault means we need to fix that binary builder repo build script.

Isn't it the Yggdrasil one? https://github.com/JuliaPackaging/Yggdrasil/tree/master/S/Sundials

**Comment by ViralBShah** [comment]
Off topic, but we should just build KLU as part of the regular SuiteSparse build, and simplify the Sundials build.

**Comment by ChrisRackauckas** [comment]
This Sundials build was the first BinaryBuilder setup, and it hasn't really been modified since. So anything like Yggdrasil isn't apart of this unless that happened outside of these repos.

No BLAS here, that's an open issue. And getting KLU out of this build would indeed be nice.

**Comment by ViralBShah** [comment]
I feel like we should get the build upgraded first. KLU would be next. But not sure if any of this would help fix the crash.

**Comment by ChrisRackauckas** [comment]
We might as well update to Sundials 5.0 at the same time too. It's an easy enough API change. It mostly just needs someone who wants to make the binaries build

**Comment by ViralBShah** [comment]
@ChrisRackauckas Should I try this again now? Will it pull Sundials 5 and the new changes? I don't have any use for this myself, but just figured I can close htis out if if it works.

**Comment by ChrisRackauckas** [comment]
Yes, it should just test it on Sundials 5.

**Comment by ViralBShah** [comment]
Well, doesn't work.

```
signal (11): Segmentation fault
in expression starting at /home/viral/.julia/packages/Sundials/0yJ3G/test/cvode_Roberts_simplified.jl:14
SUNMatGetID at /home/viral/.julia/artifacts/ee6fe6e3b73ab790eab0ab0d686f5df2933d0498/lib/libsundials_sunmatrixdense.so.3 (unknown line)
Allocations: 19394760 (Pool: 19392171; Big: 2589); GC: 42
ERROR: Package Sundials errored during testing
```

**Comment by ViralBShah** [comment]
> ```julia
> using Sundials
> function lorenz(du,u,p,t)
>  du[1] = 10.0(u[2]-u[1])
>  du[2] = u[1]*(28.0-u[3]) - u[2]
>  du[3] = u[1]*u[2] - (8/3)*u[3]
> end
> u0 = [1.0;0.0;0.0]
> tspan = (0.0,100.0)
> prob = ODEProblem(lorenz,u0,tspan)
> sol = solve(prob,CVODE_Adams())
> using Plots; plot(sol,vars=(1,2,3))
> ```
> 
> is what I'd try.

This fails now. 
```

julia> sol = solve(prob,CVODE_Adams())

[CVODES WARNING]  CVode
  Internal t = 0 and h = 0 are such that t + h = t on the next step. The solver will continue anyway.

Segmentation fault
```

**Comment by ViralBShah** [comment]
It is worth checking of 32-bit Linux binaries work fine.

**Comment by ViralBShah** [comment]
@jd-lara Any thoughts?

**Comment by jd-lara** [comment]
It seems that the `SUNLinearSolver` wrap has some problem. We would have to review this when fixing #250
