### ISSUE TITLE
IDA does not respect the `maxiters` option

### ISSUE THREAD

**Issue by YingboMa** [SciML/Sundials.jl#269]
I have set `maxiters` to 1, but clearly, IDA took more than 1 step here. :-)

```julia
julia> solve(prob,IDA(), maxiters=1).t |> length
145
```

It looks like the common interface code is correct,
https://github.com/SciML/Sundials.jl/blob/master/src/common_interface/solve.jl#L918

@jd-lara Do you know why this happens?

**Comment by jd-lara** [comment]
I am not aware of any heuristic to remove that. The documentation only mentions that if negative it disables the max limit. I would have to make a test with the direct API to confirm what is happening.
