### ISSUE TITLE
IDACalcIC does not return the value of y0 and yp0

### ISSUE THREAD

**Issue by MarcBerliner** [SciML/Sundials.jl#278]
After running IDACalcIC, the optimal value of y0 and yp0 are not saved to the variables. The calculated initial guesses are still saved somewhere, but I am not sure how to access them.

I have a large DAE system that this happens for, but I will exemplify it by modifying [ida_HEAT2D.jl](https://github.com/SciML/Sundials.jl/blob/master/test/ida_Heat2D.jl) If you print u after every iteration of heatres and run IDACalcIC, the final u0 is
`
u0_IDACalcIC = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0000000000009052e-7, 1.000000000000397e-7, 1.0000000000006511e-7, ..., 1.0000000000009052e-7, 0.0, 1.0000000000009052e-7, 1.0000000000009052e-7, 1.0000000000009052e-7, 1.0000000000009052e-7, 1.0000000000009052e-7, 1.0000000000009052e-7, 1.0000000000009052e-7, 1.0000000000009052e-7, 1.0000000000009052e-7, 0.0]
`
 compared to
`
u0_given = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.1, ..., 0.1, 0.0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.0]
`
Now, running your example shows that yres[:,1] is still equal to u0_given. The results for t > 0 do appear to be using u0_IDACalcIC however. This is the same in my model too. I am comparing a MATLAB implementation of the code using Sundials vs. my julia implementation of the code, so I am sure my final u0_IDACalcIC is correct because they match 1:1.

Iterating through IDASolve changes the value of t, y, and yp so I am a little confused why IDACalcIC does not do it as well. Is there some other way to access the converged y0 and yp0? I need them for my results.

I am using the latest Sundials and Julia 1.5.0.

**Comment by ChrisRackauckas** [comment]
Is there code you can share? Is this for the common interface?

**Comment by MarcBerliner** [comment]
I would be happy to email some code, but I do not want to put up the model publicly. I am not using the common interface because I could not find any options for constraining the variables (`IDASetConstraints`) or only taking a single step of the adaptive time stepper (`Sundials.IDASolve(..., IDA_ONE_STEP)`). If this is not the case then I would gladly switch over.

**Comment by ChrisRackauckas** [comment]
ahh, I didn't know they added `IDASetConstraints` but it's equivalent to `isoutofdomain` in our common interface, so we can get that setup. Single stepping is provided by the integrator interface https://diffeq.sciml.ai/stable/basics/integrator/

Anyways, I don't know but maybe the way to do it is to use the dense output to get the value out?

**Comment by MarcBerliner** [comment]
I had some time to test this with the common interface but I still have the same issue. What do you mean by using the dense output?

**Comment by ChrisRackauckas** [comment]
The `get dky` or whatever function for the continuous output would let you access the current value by evaluating it at the current time.

**Comment by MarcBerliner** [comment]
Perfect! For anyone else looking at this in the future, you can use `Sundials.IDAGetDky(mem, 0.0, 0, y)` to get the initial y0.
