### ISSUE TITLE
GC corruption when running PkgEval on 1.6

### ISSUE THREAD

**Issue by KristofferC** [SciML/Sundials.jl#280]
When running PkgEval on Julia 1.6 this package came up as hainvg a GC corruption: https://github.com/JuliaCI/NanosoldierReports/blob/303a819e120eac6b87b3c74c18c024ae0359e457/pkgeval/by_hash/3573793_vs_c4acbf9/logs/Sundials/1.6.0-DEV-4978cd5a4f.log#L333-L348.

**Comment by jd-lara** [comment]
Any hint on how to find the potential issue? I can try to fix it in https://github.com/SciML/Sundials.jl/pull/281

**Comment by KristofferC** [comment]
I guess first thing would be to see if it replicates reliably locally.
