### ISSUE TITLE
Document IDA options

### ISSUE THREAD

**Issue by ufechner7** [SciML/Sundials.jl#306]
I cannot find a documentation how to use:
1. arrays for atol
2. how to set inith
3. how to set maxord

for IDA.

**Comment by ufechner7** [comment]
From the manual:

IDASVtolerances
Call flag = IDASVtolerances(ida mem, reltol, abstol);
Description The function IDASVtolerances specifies scalar relative tolerance and vector absolute
tolerances.
Arguments ida mem (void *) pointer to the ida memory block returned by IDACreate.
reltol (realtype) is the scalar relative error tolerance.
abstol (N Vector) is the vector of absolute error tolerances.
Return value The return value flag (of type int) will be one of the following:
The call to IDASVtolerances was successful.
The ida memory block was not initialized through a previous call to
IDACreate.
IDA NO MALLOC The allocation function IDAInit has not been called.
IDA ILL INPUT The relative error tolerance was negative or the absolute tolerance had
a negative component.
IDA SUCCESS
IDA MEM NULL
Notes
This choice of tolerances is important when the absolute error tolerance needs to be
different for each compone

**Comment by ufechner7** [comment]
From the manual:
**Maximum order for BDF method** 
Function name: IDASetMaxOrd
Default value: 5

**Comment by ufechner7** [comment]
**Initial step size**
IDASetInitStep

Named inith in Assimulo: https://jmodelica.org/assimulo/implicit.html#assimulo.solvers.sundials.IDA.inith

**Comment by ChrisRackauckas** [comment]
Most of those are common arguments documented in the same place they always are:

https://diffeq.sciml.ai/stable/basics/common_solver_opts/

The order though is specific to IDA, so it’s documented in the same place all of the algorithm-specific arguments are, i.e. in the algorithm’s documentation.

https://diffeq.sciml.ai/stable/solvers/dae_solve/#Sundials.jl

It all follows a pattern.
