### ISSUE TITLE
Various random crashes using Sundials.CV_ADAMS method

### ISSUE THREAD

**Issue by portig** [SciML/Sundials.jl#323]
Lately I have been experiencing frequent crashes when integrating a fairly simple two degrees of freedom problem using Sundials v4.5.3. The variety and randomness of the crashes suggests to me that some code or data area is corrupted, and in a different way every time my program runs. This behavior occurs both with Julia 1.6 and 1.7 on MacOS. Similar, if not identical, behavior under Windows 10.

My program is structured similar to a sample in `simple.jl` distributed with Sundials.

Here are three samples of output from Julia when the program malfunctions (also see the attached file):
**************************
GC error (probable corruption) :
Allocations: 33448869 (Pool: 33436141; Big: 12728); GC: 26

!!! ERROR in jl_ -- ABORTING !!!
0x13b114000: Queued root: 0x1117ca810 :: 0x1105e3d30 (bits: 3)
        of type Core.SimpleVector
0x13b114018: Queued root: 0x113e503d0 :: 0x1105ff680 (bits: 3)
        of type Core.TypeMapEntry
-------------lots more similar lines--------------------------
0x13b119760: Queued root: 0x12dc41330 :: 0x1105e43f0 (bits: 3)
        of type Array{Any, 1}
0x13b119778:  r-- Stack frame 0x7ffeec05c8f0 -- 0 of 8 (direct)

signal (6): Abort trap: 6
in expression starting at REPL[2]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 33448869 (Pool: 33436141; Big: 12728); GC: 26
zsh: abort      julia-1.7
**************************
signal (11): Segmentation fault: 11
in expression starting at REPL[2]:1
jl_exit_thread0_cb at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.dylib (unknown line)
Allocations: 35213457 (Pool: 35199920; Big: 13537); GC: 31

signal (11): Segmentation fault: 11
in expression starting at REPL[2]:1
jl_exit_thread0_cb at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.dylib (unknown line)
Allocations: 35213457 (Pool: 35199920; Big: 13537); GC: 31
Quitting Julia 1.7.0-rc1 . . .             --------------- (message from my startup.jl)--------------
**************************
The loop quit early!  ---(message from `catch` block that contains the loop that implements the integration)
ERROR: MethodError: no method matching Int8(::Float64, ::Vector{Float64}, ::Vector{Float64}, ::Type{Union{UInt16, UInt32, UInt64, UInt8, SIMDTypes.Bit, VectorizationBase.AbstractSIMD{W, T}}})
Closest candidates are:
  Int8(::Float64) at float.jl:787
  (::Type{T})(::T) where T<:Number at boot.jl:770
Stacktrace:
 [1] cvodefun(t::Float64, y::Ptr{Sundials._generic_N_Vector}, yp::Ptr{Sundials._generic_N_Vector}, userfun::Sundials.UserFunctionAndData{Function})
   @ Sundials ~/.julia/packages/Sundials/YfkdE/src/simple.jl:92
 [2] CVode
   @ ~/.julia/packages/Sundials/YfkdE/src/API/cvodes.jl:166 [inlined]
 [3] CVode(cvode_mem::Sundials.Handle{Sundials.CVODEMem}, tout::Float64, yout::Sundials.NVector, tret::Vector{Float64}, itask::Int32)
   @ Sundials ~/.julia/packages/Sundials/YfkdE/src/API/cvodes.jl:171
 [4] macro expansion
   @ ~/.julia/packages/Sundials/YfkdE/src/simple.jl:15 [inlined]
 [5] cvode(f::Function, t::Vector{Float64}, y0::Vector{Float64}, reltol::Float64, abstols::Vector{Float64}; userdata::Vector{Float64}, slowFactor::Float64)
   @ Main ~/Documents/Ghost/Sorter/Drum Shutter with Spring07.jl:473
 [6] go()
   @ Main ~/Documents/Ghost/Sorter/Drum Shutter with Spring07.jl:589
 [7] top-level scope
   @ REPL[2]:1
**************************
After this last failure I was able to run the program successfully several times in a row.

Yesterday I experimented with running my program in two separate terminal windows. After having run the program successfully in one window it would not run in the other. When quitting Julia in the first window, the program ran successfully in the other. I was able to reproduce this several times with either terminal being the "first". Could not reproduce it today.

[Sundials Crashes 210926.txt](https://github.com/SciML/Sundials.jl/files/7237155/Sundials.Crashes.210926.txt)

**Comment by ChrisRackauckas** [comment]
Are you using the common interface? That should be rather stable.

**Comment by portig** [comment]
I am not sure what the common interface is. My program is structured very much like `function cvode!` in simple.jl.

**Comment by portig** [comment]
I am wondering if by "common interface" you mean the DifferentialEquations package. I tried that briefly and went back to Sundials for two reasons. One is that every time I reran the problem, there was a significant wait before results appeared, whereas with Sundials there was almost none. Secondly, it was not immediately obvious to me how to stop the simulation when some condition was reached, such as is done in Sundials with a function defined with Sundials.CVodeRootInit(mem, nRoots, g). I had used Sundials several times over the years with good success.

In the meantime, I had the opportunity to run the file on the Windows 10 machine and experienced one crash there with the `GC error (probable corruption)`. This crash occurred after having run the problem quite a few times. After the crash I had several more successful invocations. The output from the crash is in the attached file

[Sundials Crash 210927-1515 WIN10.txt](https://github.com/SciML/Sundials.jl/files/7239416/Sundials.Crash.210927-1515.WIN10.txt)

.

**Comment by ChrisRackauckas** [comment]
Are you closing Julia each time? It should only compile once. 

Terminating is just done with the `terminate!` command in a callback: https://diffeq.sciml.ai/stable/features/callback_functions/#Example-2:-Terminating-an-Integration .

But to get the direct form working, 99% chance it's a double free call. I would delete the https://github.com/SciML/Sundials.jl/blob/master/src/simple.jl#L184 call and see if that fixes it. The GC should already be calling free so that would be a redundant memory free, which if `isempty` checking on the Sundials side changed would cause it to double free.

**Comment by portig** [comment]
Thank you for your suggestion. After removing the `empty!(mem)` call the crashes have ceased so far. While I don't know what the `empty!` does, I am somewhat surprised that what looks so simple can bring down Julia.

I went back to reproduce what I perceived as slowness when using DifferentialEquations. The "slowness" occurs when I `include` my program multiple time, and amounts to 3 to 5 seconds. Similarly, when I `include` my present program using Sundials directly, the time to results is 2.5 to 3.5 seconds -- not much different. When I run the `solve` command several times from the command line, it's almost instantaneous. Also when I rerun my `cvode` command several times from the command line, the lag is negligible.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/Sundials.jl/pull/324 describes what's going on.

>The "slowness" occurs when I include my program multiple time, and amounts to 3 to 5 seconds

`include` is pasting code. I wouldn't recommend a workflow that is using a bunch of repeated include statements since that will result in recompilation.
