### ISSUE TITLE
Problem using Sundials & DifferentialEquations

### ISSUE THREAD

**Issue by paulnakroshis** [SciML/Sundials.jl#325]
When, in the REPL, I type
  julia> using Sundials
It fails to precompile: (see below) and because of this, julia> using DifferentialEquations fails to precompile too.

[ Info: Precompiling Sundials [c3572dad-4567-51f8-b174-8c6c989267f4]
ERROR: LoadError: InitError: could not load library "/Users/pauln/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib"
dlopen(/Users/pauln/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib, 1): Library not loaded: @rpath/libsuitesparseconfig.5.4.0.dylib
  Referenced from: /Users/pauln/.julia/artifacts/bd8ae81b8657ac029ad0b2592aaba09a79121a96/lib/libsundials_sunlinsolklu.3.2.0.dylib
  Reason: image not found

**Comment by paulnakroshis** [comment]
Forgot to mention I am using Julia 1.6.3 on os x 11.6.

**Comment by ChrisRackauckas** [comment]
Try `]build Sundials` again. `Reason: image not found` means the binary might be missing. If you check that file location does it exist?

**Comment by ChrisRackauckas** [comment]
Interesting. Maybe @staticfloat or @giordano might have a clue.

**Comment by paulnakroshis** [comment]
fixed problem by (unfortunately) deleting entire Julia install (and manually removing .julia folder via terminal) and reinstalling 1.6.3.  All good now.

**Comment by ChrisRackauckas** [comment]
Interesting.
