### ISSUE TITLE
libsundials_sunXXX not defined

### ISSUE THREAD

**Issue by jd-foster** [SciML/Sundials.jl#328]
Each of 
```
Sundials.libsundials_sundials
Sundials.libsundials_sunnonlinsol
Sundials.libsundials_sunmatrix
Sundials.libsundials_sunlinsol
```
returns an `UndefVarError`.
In particular, this causes errors with calling the API functions in `lib/libsundials_api.jl` that depend on these.

Versions:
Sundials v4.6.0 = "c3572dad-4567-51f8-b174-8c6c989267f4"
Sundials_jll v5.2.0+1 = "fb77eaff-e24c-56d4-86b1-d163f2edb164"

**Comment by ChrisRackauckas** [comment]
Did the download fail? Do `]build Sundials` again?

**Comment by jd-foster** [comment]
No, the `add` and `build` worked without incident, and still work without error.
(Now tried out a completely clean install in a new env on a different machine in Julia 1.5, vs 1.6 in OP.)
Can you not reproduce this?:
```julia
julia> using Sundials
julia> Sundials.libsundials_sundials
ERROR: UndefVarError: libsundials_sundials not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
 [2] top-level scope at REPL[11]:1
````

**Comment by YingboMa** [comment]
I think many functions in `lib/libsundials_api.jl` are not updated. Sundials_jll doesn't provide those symbols.

```julia
julia> names(Sundials_jll)
24-element Vector{Symbol}:
 :Sundials_jll
 :libsundials_arkode
 :libsundials_cvode
 :libsundials_cvodes
 :libsundials_ida
 :libsundials_idas
 :libsundials_kinsol
 :libsundials_nvecmanyvector
 :libsundials_nvecserial
 :libsundials_sunlinsolband
 :libsundials_sunlinsoldense
 :libsundials_sunlinsolklu
 :libsundials_sunlinsollapackband
 :libsundials_sunlinsollapackdense
 :libsundials_sunlinsolpcg
 :libsundials_sunlinsolspbcgs
 :libsundials_sunlinsolspfgmr
 :libsundials_sunlinsolspgmr
 :libsundials_sunlinsolsptfqmr
 :libsundials_sunmatrixband
 :libsundials_sunmatrixdense
 :libsundials_sunmatrixsparse
 :libsundials_sunnonlinsolfixedpoint
 :libsundials_sunnonlinsolnewton

julia>
```

**Comment by ChrisRackauckas** [comment]
The generator was updated relatively recently and tests on all of those passed?

**Comment by ChrisRackauckas** [comment]
Master seems fine: https://github.com/SciML/Sundials.jl/pull/329

**Comment by YingboMa** [comment]
I don't think any test run those functions in `lib/libsundials_api.jl`

**Comment by jd-foster** [comment]
To be more specific, the lack of just the symbol `Sundials.libsundials_sundials` (only the first of the list) impacts `lib/libsundials_api.jl`, and it affects the API functions that are the generic (not solver-specialised) functions.

**Comment by ChrisRackauckas** [comment]
@melonedo

**Comment by melonedo** [comment]
`libsundials` was also undefined on v4.5.3, before the new generator was introduced. Maybe `Sundials.libsundials_sundials` was for an old version of Sundials_jll, since the wrapper had not been updated for a while. I do not know how to find the right symbols for these functions, though.

**Comment by melonedo** [comment]
After digging into Sundials' build scripts, I found that Sundials builds one library product for each folder in its [source directory](https://github.com/LLNL/sundials/tree/master/src), while Sundials_jll only ships a few of these products. For example, the folder `sundials`, which is compiled into `libsundials_generic`(maybe renamed from `libsundials_sundials`), is not shipped in Sundials_jll.
 
As for the issue, `libsundials_sundials`, `libsundials_sunnonlinsol`, `libsundials_sunmatrix`, `libsundials_sunlinsol` can all be redirected to `libsudnials_cvode`, as this library statically links against all of the above. Or we can just update Sundials_jll to include these libraries.

**Comment by jd-foster** [comment]
I've created a search functionality for sundials symbols in the libraries [here in this gist](https://gist.github.com/jd-foster/c665c2a5842b5f381a78a884e0c41dd9).
It shows that all the function symbols using the pattern `ccall\(\(:(.*), libsundials_sundials` are in fact linked in all the shared libraries: e.g the binaries
```
    "libsundials_arkode.4.dylib"
    "libsundials_cvode.5.dylib"
    "libsundials_cvodes.5.dylib"
    "libsundials_ida.5.dylib"  
    "libsundials_idas.4.dylib" 
    "libsundials_kinsol.5.dylib" 
```
As noted by @melonedo, I think you can take your pick of setting which one, for example,
`libsundials_sundials = Sundials.libsundials_kinsol` or `libsundials_sundials = Sundials.libsundials_cvode`

The only exceptions to this linking are the BLAS/Lapack functions below, which do not appear in any of the above.
 "dcopy_64_"
 "dscal_64_"
 "scopy_64_"
 "sscal_64_"
 "dgemv_64_"
 "dtrsv_64_"
 "sgemv_64_"
 "strsv_64_"
 "dsyrk_64_"
 "ssyrk_64_"
 "dgbtrf_64_"
 "dgbtrs_64_"
 "dgeqp3_64_"
 "dgeqrf_64_"
 "dgetrf_64_"
 "dgetrs_64_"
 "dormqr_64_"
 "dpotrf_64_"
 "dpotrs_64_"
 "sgbtrf_64_"
 "sgbtrs_64_"
 "sgeqp3_64_"
 "sgeqrf_64_"
 "sgetrf_64_"
 "sgetrs_64_"
 "sormqr_64_"
 "spotrf_64_"
 "spotrs_64_"
```

**Comment by jd-foster** [comment]
Cheers all.
