### ISSUE TITLE
Issue #323 again: Frequent crashes using CV_ADAMS, mostly involving GC

### ISSUE THREAD

**Issue by portig** [SciML/Sundials.jl#332]
When issue #323 was closed I thought that the problem was solved. Not. It has come back worse than ever. Attached are three files showing the output from several different crashes on MacOS. It is completely random whether the program will run or whether one of the crashes occurs. The crashes documented in the attached files occurred when first including the program in a fresh Julia session and then invoking it, i.e., no calls SUNLinSolFree_Dense or SUNMatDestroy_Dense have occurred yet. The potential call to empty!(mem) is still commented out anyway. Sundials is updated to version 4.6.0.

The three types of failure documented here on MacOS are not the same as those on WIN10. One of those requests that it be reported when it occurs. Files attached to issue #323 document that.

The frequency of crashes under both OSs has been steadily increasing over the last couple of weeks. On the windows machine I have deleted the whole 'compiled' subdirectory. After it rebuilt itself, the error situation did not improve.

The program is structured after cvode! in simple.j
[Signal (6) crash 211130 MacOS.txt](https://github.com/SciML/Sundials.jl/files/7629880/Signal.6.crash.211130.MacOS.txt)
[Signal (11) crash 211130 MacOS.txt](https://github.com/SciML/Sundials.jl/files/7629881/Signal.11.crash.211130.MacOS.txt)
[Method error incorrect error message 211130 MacOS.txt](https://github.com/SciML/Sundials.jl/files/7629882/Method.error.incorrect.error.message.211130.MacOS.txt)
l.

**Comment by portig** [comment]
The attached file is the console output from one of today's crashes on a WIN10 machine. Julia 1.7.0 had just been freshly installed.

My Julia file that is giving me problems has gotten fairly large, over 2000 LOC. It appears that the problems with Sundials are increasing as the file gets larger. The code that invokes Sundials is being changed very little. The changes mainly involve the additions of options that cause different sets of global variables to be initialized -- not very complicated. When the program fails it is always during the call to Sundials.CVode.

[Sundials Malfunction on WIN10 211201-1330.txt](https://github.com/SciML/Sundials.jl/files/7636540/Sundials.Malfunction.on.WIN10.211201-1330.txt)

**Comment by ChrisRackauckas** [comment]
Is this using the common API?

**Comment by portig** [comment]
I am calling Sundials functions directly, not the DifferentialEquations package.

I may have finally found something that works. What now seems to work is modeled after code in `cvode_Roberts_dns.jl`. I removed the use of actual `userdata`, I am calling `CVodeInit` twice and I changed function `f` to accept NVectors and converting these to Julia vectors.

Its no working on the WIN10 machine. We'll see tonight if it also words on Mac.


CVodeInit` is called twice, `f` receives Sundials-type vectors
and translates them into Julia vectors.

**Comment by ChrisRackauckas** [comment]
If you're using it directly you have to be very careful about how and when memory is freed. The NVector wrappers setup finalizers so that the GC handles it all well, so using the wrappers is usually a better idea than doing it fully manually.

**Comment by portig** [comment]
My Julia code that is working now does not do any explicit freeing. I wouldn't know how to do that anyway. Have not found much documentation for the Julia Sundials package.

**Comment by ChrisRackauckas** [comment]
> Have not found much documentation for the Julia Sundials package.

It's fairly well-documented here: https://diffeq.sciml.ai/stable/solvers/ode_solve/#ode_solve_sundials

The direct API is essentially for creating the common interface wrappers, though you are free to use it directly using the SUNDIALS documentation as a guide, though we do not recommend doing it for very many reasons.

**Comment by portig** [comment]
Thanks for your responses!

It's all working OK now also on the Mac.
