### ISSUE TITLE
[aarch64]: cfunction: closures are not supported on this platform breaks Sundials

### ISSUE THREAD

**Issue by portig** [SciML/Sundials.jl#339]
This seems to be a pretty fundamental problem when trying to run on Apple silicon. Is there a way that Sundials could handle the CVodeInit call without closure? As a workaround, I can still use Rosetta 2 and bypass this problem.

Here is the error output:

ERROR: cfunction: closures are not supported on this platform
Stacktrace:
 [1] CVRhsFn_wrapper
   @ ~/.julia/packages/Sundials/PEymo/src/types_and_consts_additions.jl:10 [inlined]
 [2] CVodeInit(cvode_mem::Sundials.Handle{Sundials.CVODEMem}, f::Function, t0::Float64, y0::Vector{Float64})
   @ Sundials ~/.julia/packages/Sundials/PEymo/lib/libsundials_api.jl:1376
 [3] cvode(f::Function, t::Vector{Float64}, y0::Vector{Float64}, reltol::Float64, abstols::Vector{Float64}; userdata::Nothing, slowFactor::Float64)
   @ Main ~/Documents/file.jl:1820
 [4] go()
   @ Main ~/Documents/file.jl:2058
 [5] top-level scope
   @ REPL[4]:1

**Comment by ChrisRackauckas** [comment]
I don't think there's a way around it. It will get fixed in Base. But since CVODE is slower than alternatives at this point, it's not a major issue for most users looking for features or performance.
