### ISSUE TITLE
Failed to precompile on Arch Linux

### ISSUE THREAD

**Issue by scratch-er** [SciML/Sundials.jl#358]
When I tried to import this package on Julia installed with pacman (the package manager of Arch Linux), it fails to precompile.
```
[ Info: Precompiling Sundials [c3572dad-4567-51f8-b174-8c6c989267f4]
ERROR: LoadError: InitError: could not load library "/home/scratcher/.julia/artifacts/cb7fc2801ca0133a5bdea4bc4585d07c08284cfa/lib/libsundials_sunlinsollapackband.so"
libopenblas64_.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
 [2] __init__()
   @ Sundials_jll ~/.julia/packages/Sundials_jll/rXn1i/src/wrappers/x86_64-linux-gnu-libgfortran5.jl:99
 [3] top-level scope (repeats 2 times)
   @ none:1
during initialization of module Sundials_jll
in expression starting at /home/scratcher/.julia/packages/Sundials/k9hc3/src/Sundials.jl:3
ERROR: Failed to precompile Sundials [c3572dad-4567-51f8-b174-8c6c989267f4] to /home/scratcher/.julia/compiled/v1.7/Sundials/jl_511N5H.

```
However, it works on Julia downloaded from julialang.org
I've noticed that this error occured because `libopenblas64_.so` cannot be found. However, it was installed to `usr/lib/julia/libopenblas64_.so`.

Should I report this problem to the packager instead?

**Comment by YingboMa** [comment]
Are you using Julia that's from the office webpage?

**Comment by scratch-er** [comment]
> Are you using Julia that's from the official webpage?

Sundials.jl *works* on Julia downloaded from the official website. But it dosen't work on Julia installed via system package manager. However, most of the other packages that I've installed work on both.
The cause might be that Sundials.jl was only designed for the official Julia release. In this case, it's support for third-party builds of Julia needs to be improved. Or it might be the packager's fault.

我在上面的内容中已经说明了，Sundials.jl在官网下载的Julia上是没有问题的。但是在发行版打包的Julia上提示找不到库。这个问题也许是Sundials.jl中的某些代码仅仅考虑到在官网下载的Julia，但也可能是因为发行版打包的问题。我们需要先确定问题在哪。

**Comment by ChrisRackauckas** [comment]
> However, most of the other packages that I've installed work on both.

No, the one in the package manager is purposefully broken. It's built with a version of LLVM that is incorrect and does not have the right patches to have numerical correctness. 

https://github.com/SciML/Sundials.jl/issues/334
https://wiki.archlinux.org/title/Julia#Installation

It even says so on the package manager website.

> Warning: Package [julia](https://archlinux.org/packages/?name=julia) is compiled against system libraries and is therefore unsupported by the upstream. While it may be suitable for basic usage it is incompatible with external packages (e.g. MKL, LLVM, LLVMExtra, or packages that depend on these, like CUDA or Flux) which rely on Julia's bundled versions of its dependencies. Bugs reported against this binary will be [closed](https://github.com/JuliaLinearAlgebra/MKL.jl/issues/105#issuecomment-1025985667).

I am not sure what to say other than, they purposefully have a broken build, and therefore it's a broken build, and thus it breaks downstream, and I can't do anything about it other than to tell Arch Linux to delete the broken build.

**Comment by ChrisRackauckas** [comment]
Is it possible to put a try/catch around jll imports @staticfloat ? I would like to try/catch it and throw the error.

```
Error: Sundials_jll failed to load. The most common cause for this issue is because of known broken Julia builds purposefully provided by Linux package managers. For example, Arch Linux builds with an unpatched and incorrect version of LLVM which is known to cause issues, as is mentioned in their package manager website on Julia installation: https://wiki.archlinux.org/title/Julia#Installation. For this reason, we recommend that you instead use a non-broken installation of Julia by installing the official binaries from https://julialang.org/downloads/. If you use these binaries and still have an issue, please open an issue.
```

**Comment by scratch-er** [comment]
> Is it possible to put a try/catch around jll imports @staticfloat ? I would like to try/catch it and throw the error.
> 
> ```
> Error: Sundials_jll failed to load. The most common cause for this issue is because of 
> known broken Julia builds purposefully provided by Linux package managers. For example,
> Arch Linux builds with an unpatched and incorrect version of LLVM which is known to cause 
> issues, as is mentioned in their package manager website on Julia installation: 
> https://wiki.archlinux.org/title/Julia#Installation. For this reason, we recommend that you 
> instead use a non-broken installation of Julia by installing the official binaries from 
> https://julialang.org/downloads/. If you use these binaries and still have an issue, please open an issue.
> ```

Good Idea.It saves the user a lot of time from troubleshooting.
