### ISSUE TITLE
CVODE cannot use jac_prototype?

### ISSUE THREAD

**Issue by JianghuiDu** [SciML/Sundials.jl#372]
I tried to use `GMRES` with `JacVecOperator` but `mul!` throws error because of empty operator.
The code here does look strange to me:
```julia
use_jac_prototype = (isa(prob.f.jac_prototype, SparseArrays.SparseMatrixCSC) &&
                         LinearSolver ∈ SPARSE_SOLVERS)
    userfun = FunJac(f!,
                     prob.f.jac,
                     prob.p,
                     nothing,
                     use_jac_prototype ? prob.f.jac_prototype : nothing,
                     alg.prec,
                     alg.psetup,
                     u0,
                     _u0)
```
and the jacobian vector product
```julia
    if typeof(prob.f.jac_prototype) <: DiffEqBase.AbstractDiffEqLinearOperator
        function getcfunjtimes(::T) where {T}
            @cfunction(jactimes,
                       Cint,
                       (N_Vector, N_Vector, realtype, N_Vector, N_Vector, Ref{T}, N_Vector))
        end
        jtimes = getcfunjtimes(userfun)
        CVodeSetJacTimes(mem, C_NULL, jtimes)
    end
```
When my `jac_prototype` is `JacVecOperator` and my method is `GMRES`, then `use_jac_prototype  = false`, and `userfun` will have an empty `jac_prototype`. So when creating function `jactimes`, you are missing the actual `jac_prototype`. 

Is my understanding correct? It would appear `use_jac_prototype` is true only when using `KLU` with sparsity pattern as `jac_prototype`?

**Comment by ChrisRackauckas** [comment]
It uses jac_prototype. GMRES just doesn't use the Jaocbian at all. You'd have to use KLU to actually use the sparsity pattern.

**Comment by JianghuiDu** [comment]
`GMRES` doesn't use the full jacobian but it does use the jacobian vector product, right?

**Comment by ChrisRackauckas** [comment]
yes it uses the jvp, which is why it ignores the sparsity pattern.

**Comment by ChrisRackauckas** [comment]
Sundials has a bit of its own rules because it does the jvp internal to the C++ code

**Comment by JianghuiDu** [comment]
You mean we can't pass `jvp` to Sundials? but isn't this code meant to do this?
```julia
    if typeof(prob.f.jac_prototype) <: DiffEqBase.AbstractDiffEqLinearOperator
        function getcfunjtimes(::T) where {T}
            @cfunction(jactimes,
                       Cint,
                       (N_Vector, N_Vector, realtype, N_Vector, N_Vector, Ref{T}, N_Vector))
        end
        jtimes = getcfunjtimes(userfun)
        CVodeSetJacTimes(mem, C_NULL, jtimes)
    end
```

**Comment by ChrisRackauckas** [comment]
oh yes it does. I'm not sure how well tested that piece is, but it at least tries to let you override the jvp.

**Comment by JianghuiDu** [comment]
But at the moment because of 
```julia
use_jac_prototype = (isa(prob.f.jac_prototype, SparseArrays.SparseMatrixCSC) &&
                         LinearSolver ∈ SPARSE_SOLVERS)
``` 
The jacobian vector product `CVodeSetJacTimes` only works for `KLU`. That's why I'm asking why it isn't allow for `GMRES` instead.

**Comment by ChrisRackauckas** [comment]
oh, that's a mistake.

**Comment by JianghuiDu** [comment]
I modified the code to let `use_jac_prototype = true` always and it worked. So this should be an easy fix? I'm just not sure if there're other reasons to not let `use_jac_prototype = true`

**Comment by JianghuiDu** [comment]
I'm puzzled why `jac_prototype` can be an operator for Jacobian vector product, at the same time you can have an `jvp` argument:
```julia
ODEFunction{iip,specialize}(f;
                           mass_matrix = __has_mass_matrix(f) ? f.mass_matrix : I,
                           analytic = __has_analytic(f) ? f.analytic : nothing,
                           tgrad= __has_tgrad(f) ? f.tgrad : nothing,
                           jac = __has_jac(f) ? f.jac : nothing,
                           jvp = __has_jvp(f) ? f.jvp : nothing,
                           vjp = __has_vjp(f) ? f.vjp : nothing,
                           jac_prototype = __has_jac_prototype(f) ? f.jac_prototype : nothing,
                           sparsity = __has_sparsity(f) ? f.sparsity : jac_prototype,
                           paramjac = __has_paramjac(f) ? f.paramjac : nothing,
                           syms = __has_syms(f) ? f.syms : nothing,
                           indepsym= __has_indepsym(f) ? f.indepsym : nothing,
                           paramsyms = __has_paramsyms(f) ? f.paramsyms : nothing,
                           colorvec = __has_colorvec(f) ? f.colorvec : nothing,
                           sys = __has_sys(f) ? f.sys : nothing)
```
It seems `jvp` is a late addition. I don't remember it's there in previous versions.

**Comment by ChrisRackauckas** [comment]
`jvp` was only recently added to the interface, and it's for the parameter Jacobian `f_p * v`
