### ISSUE TITLE
CVRhsFn_wrapper unsafe use of @cfunction($f, ...)

### ISSUE THREAD

**Issue by sjdaines** [SciML/Sundials.jl#381]
See eg CVRhsFn_wrapper:

https://github.com/SciML/Sundials.jl/blob/64c98c838f811b8b4c05dbd67a85df64acf0b434/src/types_and_consts_additions.jl#L9-L10

which is used in
https://github.com/SciML/Sundials.jl/blob/64c98c838f811b8b4c05dbd67a85df64acf0b434/lib/libsundials_api.jl#L1668-L1671

The problem is that a temporary Base.CFunction closure is returned by @cfunction($f, ...), which may be garbage collected so it is not safe to return the enclosed pointer (somewhat similar to the problem with NVector addressed by https://github.com/SciML/Sundials.jl/pull/380, but more fundamental as the RHS function needs to persist for the whole lifetime of the solver use).

Suggested fix is to remove CVRhsFn_wrapper (which is only used by a few tests of the low-level interface), and require that the caller either uses the @cfunction(f, ...) form to generate a C pointer (ie f known at compile time and the runtime Julia RHS function passed in to Sundials C code as part of the opaque user data, this is what the high-level interface does), or manages the lifetime of the @cfunction explicitly.

Addressed by PR https://github.com/SciML/Sundials.jl/pull/384

**Comment by ChrisRackauckas** [comment]
Fixed thanks. I wonder if this will end up fixing the ability to use Sundials' sensitivity analysis stuff too. It would be interesting to try and get https://github.com/SciML/Sundials.jl/blob/master/test/cvodes_dns.jl up and running
