### ISSUE TITLE
Difficulties using IDA for computing smooth Cholesky decompositions

### ISSUE THREAD

**Issue by andreasvarga** [SciML/Sundials.jl#402]
The computational problem is described [here](https://math.stackexchange.com/questions/4695086/computation-of-smooth-cholesky-factorizations). The function `pcplyap`, used in what follows, computes the Cholesky factor of the nonnegative definite solution of a periodic differential Lyapunov equation. This function relies on the IDA implicit DAE solver. In the example given below, the Lyapunov differential equation is solved repeatedly for `i = 1, ... , 100` on intervals `[(i-1)*dt,i*dt]`, where `dt = 2π/100` and in each case a consistent initialization of IDA is ensured by slightly perturbing  the "normal" initialization with a zero matrix.   

To overcome various IDA failures, I am calling IDA via the common interface as `IDA(;max_nonlinear_iters = 10, nonlinear_convergence_coefficient),` where   `nonlinear_convergence_coefficient` is increased 10 times if a failure occurs and the computation is repeated with the increased value. Maximum 3 iterations are allowed, but often the second iteration is already successful. This strategy sometimes succeeds to compute a satisfactory solution. A typical run is shown below for  `nonlinear_convergence_coefficient = 0.33` (the default value):
```
julia> @time Ut = pcplyap(At,Bt; adj = false, K = 100, reltol = 1.e-10, abstol = 1.e-10);

[IDAS ERROR]  IDASolve
  At t = 0.753982 and h = 4.47541e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 3.3)

[IDAS ERROR]  IDASolve
  At t = 2.38761 and h = 2.39983e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 3.3)
  5.178094 seconds (59.90 M allocations: 1.961 GiB, 7.77% gc time, 2.62% compilation time: 100% of which was recompilation)

julia> @time Ut = pcplyap(At,Bt; adj = false, K = 100, reltol = 1.e-10, abstol = 1.e-10);

[IDAS ERROR]  IDASolve
  At t = 0.816814 and h = 6.47231e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 0.33)

[IDAS ERROR]  IDASolve
  At t = 0.879646 and h = 6.70747e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 0.33)

[IDAS ERROR]  IDASolve
  At t = 0.942478 and h = 6.91945e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 0.33)

[IDAS ERROR]  IDASolve
  At t = 2.19911 and h = 6.91945e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 0.33)

[IDAS ERROR]  IDASolve
  At t = 2.26195 and h = 6.70747e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 0.33)

[IDAS ERROR]  IDASolve
  At t = 2.32478 and h = 6.47231e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 0.33)
  7.774406 seconds (91.98 M allocations: 2.995 GiB, 8.11% gc time, 1.69% compilation time: 100% of which was recompilation)
```
With `nonlinear_convergence_coefficient = 3.3`, the behaviour is better: 
```
julia> @time Ut = pcplyap(At,Bt; adj = false, K = 100, reltol = 1.e-10, abstol = 1.e-10);

[IDAS ERROR]  IDASolve
  At t = 0.753982 and h = 4.47541e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 3.3)

[IDAS ERROR]  IDASolve
  At t = 2.38761 and h = 2.39983e-314, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 3.3)
  5.321037 seconds (59.90 M allocations: 1.961 GiB, 8.44% gc time, 2.63% compilation time: 100% of which was recompilation)

``` 
while with `nonlinear_convergence_coefficient = 33.0`, the behaviour is different: 
```
julia> @time Ut = pcplyap(At,Bt; adj = false, K = 100, reltol = 1.e-10, abstol = 1.e-10);

[IDAS ERROR]  IDASolve
  At t = 0.188496 and h = 3.45614e-142, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 33.0)
(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.MaxIters, 33.0)
(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.MaxIters, 33.0)
(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.MaxIters, 33.0)

[IDAS ERROR]  IDASolve
  At t = 3.70708 and h = 2.12494e-108, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 33.0)

[IDAS ERROR]  IDASolve
  At t = 5.7177 and h = 2.12494e-108, the corrector convergence failed repeatedly or with |h| = hmin.

(iter, sol.retcode, nonlinear_convergence_coefficient) = (1, SciMLBase.ReturnCode.ConvergenceFailure, 33.0)
  8.820958 seconds (101.46 M allocations: 3.311 GiB, 7.60% gc time)

```

The good news are that in all these runs, the computed solutions are usable and fit well with the symmetric solution computed with another method! 

I have two questions regarding such a behaviour of IDA. 

1. Are any recommendations or known tricks to select  `nonlinear_convergence_coefficient` or other parameters to avoid the above failures ?
2. Is any way to get rid of the error messages of the form 
```
[IDAS ERROR]  IDASolve
  At t = 0.188496 and h = 3.45614e-142, the corrector convergence failed repeatedly or with |h| = hmin.

```
? 

Thanks in advance for any help.

**Comment by ChrisRackauckas** [comment]
Are you sure that your system is an index-1 DAE? If it's a higher index, then you'd expect to get this kind of behavior.

**Comment by andreasvarga** [comment]
Sorry for this late reply, but I was not reachable for communication in the last three weeks.

This problem, in its simplest form, is essentially to integrate a square-root quantity as described in [#954](https://github.com/SciML/DifferentialEquations.jl/issues/954), on an interval `[0,T]`, with _zero_ initial condition. I am only interestd in the final value at `T`. I was not able to find a solution of this problem in the literature for the matrix case formulated [here](https://math.stackexchange.com/questions/4695086/computation-of-smooth-cholesky-factorizations).

My understanding is that there are two basic difficulties when using implicit solvers to solve this problem: 
1. The initial condition of derivative is infinite for zero initial condition; 
2. Non-uniqueness of the solution of the equation for the derivative computation, because of non-uniqueness of square-root (both + an - values are OK).

The first aspect I tried to handle using a large value of derivative corresponding to a small perturbation of the intial condition. This allows to consistently initialize IDA, which then starts the integration without any complaints. This works well for my problem setting, because the effect of the initial perturbation is largely attenuated (practically disapears if the final time `T` is sufficiently large). This approach can be also extended to the matrix case. 

For the second aspect I relied on the internal linear solver of IDA, which for the scalar case works well, but produced the errors already mentioned. I managed to overcome failures for a 2x2 matrix case, by simply catching the error and increasing a solver parameter by a factor of 10. This certainly is not a general approach, but occasionaly works. I implemented also an explicit solver based solution, where similar convergence issues may occur (probably because of lack of smoothness of derivatives). 

I hope very much that a robust solution of this problem, formulated either as ODE or DAE, should be possible, with the same benefits for accuracy as in the case of positive algebraic Lyapunov equations. 

Answering your question: To be honest, I don't know if this problem is an index-1 DAE or not. What would imply the fact that it can be also reformulated as an explicit ODE, with the caveat of possible non-uniqueness of derivatives?

**Comment by ChrisRackauckas** [comment]
Equations with a starting singularity often need to use a special approach, such as by specifying it as a BVP and solving via a boundary value problem solver. The non-uniqueness issue is what would generally be handled through state selection types of things. 

But we can take this elsewhere. This doesn't seem to be an issue with IDA but instead is the type of problem where an algorithm like IDA would be unstable.
